"""
StreamSentinel — Prometheus Metrics Instrumentation.

Provides counters, histograms, and gauges for platform observability.
All metrics use the 'streamsentinel_' prefix for Prometheus namespace isolation.
"""
from prometheus_client import Counter, Histogram, Gauge

# ─── Transaction Processing ─────────────────────────────────────────────────
TRANSACTIONS_PROCESSED = Counter(
    "streamsentinel_transactions_processed_total",
    "Total number of transactions processed through the detection pipeline"
)

TRANSACTIONS_ERRORS = Counter(
    "streamsentinel_transactions_errors_total",
    "Total number of transaction processing errors"
)

TRANSACTIONS_IN_PROGRESS = Gauge(
    "streamsentinel_transactions_in_progress",
    "Number of transactions currently being processed"
)

# ─── Decision Outcomes ──────────────────────────────────────────────────────
DECISIONS_TOTAL = Counter(
    "streamsentinel_decisions_total",
    "Total number of decisions by type",
    ["decision"]
)

# ─── Detection Latency ──────────────────────────────────────────────────────
DETECTION_LATENCY = Histogram(
    "streamsentinel_detection_latency_seconds",
    "Detection pipeline latency in seconds",
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]
)

# ─── Alerts ──────────────────────────────────────────────────────────────────
ALERTS_TOTAL = Counter(
    "streamsentinel_alerts_total",
    "Total alerts generated by severity",
    ["severity"]
)

# ─── OTP ─────────────────────────────────────────────────────────────────────
OTP_VERIFICATION_TOTAL = Counter(
    "streamsentinel_otp_verification_total",
    "OTP verification attempts by result",
    ["result"]
)

# ─── Webhook ─────────────────────────────────────────────────────────────────
WEBHOOK_TOTAL = Counter(
    "streamsentinel_webhook_total",
    "Webhook dispatch attempts by status",
    ["status"]
)

# ─── API ─────────────────────────────────────────────────────────────────────
API_REQUESTS_TOTAL = Counter(
    "streamsentinel_api_requests_total",
    "Total API requests by method, endpoint, and status code",
    ["method", "endpoint", "status_code"]
)

API_REQUEST_DURATION = Histogram(
    "streamsentinel_api_request_duration_seconds",
    "API request duration in seconds",
    ["method", "endpoint"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0]
)

API_ERRORS_TOTAL = Counter(
    "streamsentinel_api_errors_total",
    "Total API errors (5xx responses)"
)

# ─── Review ──────────────────────────────────────────────────────────────────
REVIEW_ACTIONS_TOTAL = Counter(
    "streamsentinel_review_actions_total",
    "Review actions taken by type",
    ["action"]
)

# ─── Database ────────────────────────────────────────────────────────────────
DB_ERRORS_TOTAL = Counter(
    "streamsentinel_db_errors_total",
    "Database operation errors"
)
